name: Build app on code push

on: [push]

env:
  APP_NAME: health

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}
      - name: Run build
        run: cd ${{ env.APP_NAME }} && make appstore
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: ${{ env.APP_NAME }}/build/artifacts/appstore/health.tar.gz
